import BigNumber from 'bignumber.js';

export default {
  EXCHANGES: {
    ZERO_EX: 1,
    KYBER: 2,
  },

  WBTC: {
    PRICE: new BigNumber(3711),
    FULL_TOKEN_UNITS: new BigNumber(10 ** 8),
  },
  DEFAULT_WBTC_UNIT: new BigNumber(1),

  WETH: {
    FULL_TOKEN_UNITS: new BigNumber(10 ** 18),
    PRICE: new BigNumber(128),
  },
  DEFAULT_COLLATERAL_NATURAL_UNIT: new BigNumber(10 ** 12), 
  WETH_DOMINANT_COLLATERAL_NATURAL_UNIT: new BigNumber(10 ** 12),

  DAI: {
    FULL_TOKEN_UNITS: new BigNumber(10 ** 18),
    PRICE: new BigNumber(1),
  },

  DEFAULT_REBALANCING_NATURAL_UNIT: new BigNumber(10 ** 6),
  REBALANCING_SET_USD_PRICE: new BigNumber(100),
  DEFAULT_AUCTION_PRICE_NUMERATOR: 1374,
  DEFAULT_AUCTION_PRICE_DENOMINATOR: 1000,
  SET_FULL_TOKEN_UNITS: new BigNumber(10 ** 18),
  ONE_MINUTE_IN_SECONDS: 60,
  THIRTY_MINUTES_IN_SECONDS: 1800,
  ONE_HOUR_IN_SECONDS: 3600,
  ONE_DAY_IN_SECONDS: 86400,
  THIRTY_DAYS_IN_SECONDS: 2592000,
  MINIMUM_REBALANCING_NATURAL_UNIT: 10000,
  MAXIMUM_REBALANCING_NATURAL_UNIT: 100000000000000
};