export const CONTRACT = {
  BitEthInitialCollateralSet: 'BitEthInitialCollateralSet',
  BitEthRebalanceManager: 'BitEthRebalanceManager',
  BitEthRebalancingSetToken: 'BitEthRebalancingSetToken',
  Core: 'Core',
  CoreIssuanceLibrary: 'CoreIssuanceLibrary',
  ERC20Wrapper: 'ERC20Wrapper',
  ETHDaiInitialCollateralSet: 'ETHDaiInitialCollateralSet',
  ETHDaiRebalanceManager: 'ETHDaiRebalanceManager',
  ETHDaiRebalancingSetToken: 'ETHDaiRebalancingSetToken',
  ExchangeIssuanceLibrary: 'ExchangeIssuanceLibrary',
  ExchangeIssuanceModule: 'ExchangeIssuanceModule',
  KyberNetworkWrapper: 'KyberNetworkWrapper',
  LinearAuctionPriceCurve: 'LinearAuctionPriceCurve',
  PayableExchangeIssuance: 'PayableExchangeIssuance',
  RebalanceAuctionModule: 'RebalanceAuctionModule',
  RebalancingHelperLibrary: 'RebalancingHelperLibrary',
  RebalancingSetTokenFactory: 'RebalancingSetTokenFactory',
  RebalancingTokenIssuanceModule: 'RebalancingTokenIssuanceModule',
  SetTokenFactory: 'SetTokenFactory',
  StandardFailAuctionLibrary: 'StandardFailAuctionLibrary',
  StandardPlaceBidLibrary: 'StandardPlaceBidLibrary',
  StandardProposeLibrary: 'StandardProposeLibrary',
  StandardSettleRebalanceLibrary: 'StandardSettleRebalanceLibrary',
  StandardStartRebalanceLibrary: 'StandardStartRebalanceLibrary',
  TransferProxy: 'TransferProxy',
  Vault: 'Vault',
  WhiteList: 'WhiteList'  ,
  ZeroExExchangeWrapper: 'ZeroExExchangeWrapper',
};

export const DEPENDENCY = {
  DAI: 'DAI',
  KYBER_PROXY: 'KYBER_PROXY',
  WBTC: 'WBTC',
  WBTC_MEDIANIZER: 'WBTC_MEDIANIZER',
  WETH: 'WETH',  
  WETH_MEDIANIZER: 'WETH_MEDIANIZER',
  ZERO_EX_EXCHANGE: 'ZERO_EX_EXCHANGE',
  ZERO_EX_PROXY: 'ZERO_EX_PROXY',
  ZERO_EX_ZRX: 'ZERO_EX_ZRX',
};