var config = {
  EXCHANGES: {
    ZERO_EX: 1,
    KYBER: 2,
    TAKER_WALLET: 3,
  },
  WBTC_PRICE: 3711,
  WETH_PRICE: 128,
  DEFAULT_AUCTION_PRICE_NUMERATOR: 1374,
  DEFAULT_AUCTION_PRICE_DENOMINATOR: 1000,
  ONE_MINUTE_IN_SECONDS: 60,
  THIRTY_MINUTES_IN_SECONDS: 1800,
  ONE_HOUR_IN_SECONDS: 3600,
  ONE_DAY_IN_SECONDS: 86400,
  THIRTY_DAYS_IN_SECONDS: 2592000,
  TIMELOCK_PERIOD_DEPLOYMENT: 0,
}

module.exports = config;